services:
  api_host: "localhost"
  api_base_path: "/nomad-oasis"
  upload_limit: 1000
  upload_members_group_search_enabled: true

oasis:
  is_oasis: true
  uses_central_user_management: true
  allowed_users:
    - a.pedico@inrim.it
    - d.pugliese@inrim.it
    - a.airi@inrim.it
    - i.murataj@inrim.it
    - francescadechiara@cnr.it
    - luisa.caracciuolo@cnr.it
    - ferrario@fbk.eu
    - alfredo.picano@cnr.it
    - vittorio.morandi@cnr.it
    - piera.maccagnani@cnr.it
    - alessandro.gradone@cnr.it
    - nicola.gilli@cnr.it
    - sebastian.brueckner@physik.hu-berlin.de
    - joseph.rudzinski@physik.hu-berlin.de
    - abbas.gholami@glaidedata.com
    - enzo.rotunno@nano.cnr.it
    - giovanni.bertoni@nano.cnr.it
    - daniele.duranti@uniroma3.it
    - marco.sebastiani@uniroma3.it
    - pietro.zaccagnini@polito.it
    - giulia.massaglia@polito.it
    - gianluca.sbardella@uniroma1.it
    - tommaso.salzillo@unibo.it
    - francesco.valle@cnr.it
    - francesca.rossi@imem.cnr.it
    - luca.seravalli@imem.cnr.it
    - emanuela.colasante@artov.ism.cnr.it
    - antonio.santagata@ism.cnr.it
    - gianluca.landi@stems.cnr.it
    - valentina.gargiulo@stems.cnr.it
    - massimo.urciuolo@stems.cnr.it
    - salvatoreethan.panasci@imm.cnr.it
    - patrick.fiorenza@imm.cnr.it
    - filippo.giannazzo@imm.cnr.it
    - marino.lavorgna@cnr.it
    - diego.pugliese@polito.it
    - roberto.verucchi@cnr.it
    - lucia.nasi@cnr.it
    - gennaro.gentile@cnr.it
    - francesca.rossi@cnr.it
    - gianluca.landi@cnr.it
    - emanuela.colasante@cnr.it
    - gianluca,sbardella@uniroma1.it
    - giovanni.bertoni@cnr.it
    - luisa.carracciuolo@cnr.it
    - massimo.urciuolo@cnr.it
    - a.pedico@inrim.it
    - d.pugliese@inrim.it
    - a.airi@inrim.it
    - i.murataj@inrim.it
    - francescadechiara@cnr.it
    - luisa.caracciuolo@cnr.it
    - ferrario@fbk.eu
    - alfredo.picano@cnr.it
    - vittorio.morandi@cnr.it
    - piera.maccagnani@cnr.it
    - alessandro.gradone@cnr.it
    - nicola.gilli@cnr.it
    - sebastian.brueckner@physik.hu-berlin.de
    - joseph.rudzinski@physik.hu-berlin.de
    - abbas.gholami@glaidedata.com
    - enzo.rotunno@nano.cnr.it
    - giovanni.bertoni@nano.cnr.it
    - daniele.duranti@uniroma3.it
    - marco.sebastiani@uniroma3.it
    - pietro.zaccagnini@polito.it
    - giulia.massaglia@polito.it
    - gianluca.sbardella@uniroma1.it
    - tommaso.salzillo@unibo.it
    - francesco.valle@cnr.it
    - francesca.rossi@imem.cnr.it
    - luca.seravalli@imem.cnr.it
    - emanuela.colasante@artov.ism.cnr.it
    - antonio.santagata@ism.cnr.it
    - gianluca.landi@stems.cnr.it
    - valentina.gargiulo@stems.cnr.it
    - massimo.urciuolo@stems.cnr.it
    - salvatoreethan.panasci@imm.cnr.it
    - patrick.fiorenza@imm.cnr.it
    - filippo.giannazzo@imm.cnr.it
    - marino.lavorgna@cnr.it
    - giulia.massaglia@polito.it
    - roberto.verucchi@cnr.it
    - lucia.nasi@cnr.it
    - gennaro.gentile@cnr.it
    - francesca.rossi@cnr.it
    - gianluca.landi@cnr.it
    - emanuela.colasante@cnr.it
    - gianluca.sbardella@uniroma1.it
    - giovanni.bertoni@cnr.it
    - luisa.carracciuolo@cnr.it
    - massimo.urciuolo@cnr.it
    - alfredo.ronca@cnr.it
    - mandeep.singh@cnr.it
    - giacomo.spisni@polito.it
    - marialaura.dilorenzo@cnr.it
    - loredana.schiavo@cnr.it
    - gennaro.rollo@cnr.it
    - pietro.russo@cnr.it
    - mariamelia.stanzione@cnr.it
    - elena.ferrari@cnr.it
    - gianfranco.carotenuto@cnr.it
    - roberto.desantis@cnr.it
    - nicologalvani@cnr.it
    - valentina.abbate@cnr.it
    - mario.deangioletti@cnr.it
    - federico.olivieri@cnr.it
    - roberto.avolio@cnr.it
    - mariaemanuela.errico@cnr.it
    - eugenio.amendola@cnr.it
    - chiara.santillo@cnr.it
    - daniela.capuano@cnr.it
    - mariarosaria.marcedula@cnr.it
    - annamaria.sabetta@cnr.it
    - letizia.verdolotti@cnr.it
    - giovannagiuliana.buonocore@cnr.it
    - salvatoreethan.panasci@cnr.it
    - fabiana.tescione@cnr.it
    - marianna.pannico@cnr.it
    - mariagrazia.raucci@cnr.it
    - mirko.seri@cnr.it
    - alberto.riminucci@cnr.it

north:
  jupyterhub_crypt_key: "978bfb2e13a8448a253c629d8dd84ff89587f30e635b753153960930cad9d36d"
  tools:
    options:
      jupyter:
        image: ghcr.io/glaidedata/nomad-oasis-image-ientrance/jupyter:main

meta:
  deployment: "oasis"
  deployment_url: "https://my-oasis.org/api"
  maintainer_email: "me@my-oasis.org"

logstash:
  enabled: false

temporal:
  enabled: true

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1

plugins:
  exclude:
    - parsers/fhi-vibes
